language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t srikar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true srikar/react-test npm test

after_success:
  - docker build -t srikar/multi-client:latest ./client
  - docker build -t srikar/multi-nginx:latest ./nginx
  - docker build -t srikar/multi-server:latest ./server
  - docker build -t srikar/multi-worker:latest ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push srikar/multi-client:latest
  - docker push srikar/multi-nginx:latest
  - docker push srikar/multi-server:latest
  - docker push srikar/multi-worker:latest