language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t srikar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true srikar/react-test npm test

after_success:
  - docker build -t srikar199410/multi-client ./client
  - docker build -t srikar199410/multi-nginx ./nginx
  - docker build -t srikar199410/multi-server./server
  - docker build -t srikar199410/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push srikar199410/multi-client
  - docker push srikar199410/multi-nginx
  - docker push srikar199410/multi-server
  - docker push srikar199410/multi-worker